### ISSUE TITLE
Addons - tags administration

### ISSUE THREAD

**Issue by hrach** [componette/componette.com#23]
How can I edit tags of my packages?

**Comment by chemix** [comment]
Will be simple admin for selected admins.

**Comment by hrach** [comment]
If so, it doesn't make sence to allow add tags in new package form, isn't it? )

**Comment by chemix** [comment]
why? 

Someone create new package and fill some tags. Admin check this tags and confirm package as approved.

**Comment by hrach** [comment]
I don't like the feeling I can something add and cannot edit it. Still, pretty weird that as a author I cannot do it, but I understand it would require some github auth ...

**Comment by f3l1x** [comment]
I dont wanna any admin for authors. Like you say, github auth and many other things..

Theres no sure that anyone fill tags. I would like to load tags from composer, but again, not filled everywhere.

If you have better idea, just do it. :)

**Comment by fprochazka** [comment]
@f3l1x loading tags from composer is a good solution :+1:

**Comment by Achse** [comment]
And what about the case that author (me :smile_cat:) just forgot to add some tags.

**Comment by f3l1x** [comment]
For everyone: if you have forgot some tags or your package has an incorrect ones, please type it here and I'll change it. 

Thanks.

**Comment by hrach** [comment]
- https://componette.com/nextras/secured-links/ #security
thanks

**Comment by Achse** [comment]
https://componette.com/achse/json-assert/

* api
* testing (missing)

Thank you.

**Comment by fprochazka** [comment]
* https://componette.com/kdyby/doctrine/
    * orm 

thanks :)

**Comment by f3l1x** [comment]
@hrach @Achse @fprochazka 

Added. Thank you.

**Comment by JZechy** [comment]
* https://componette.com/jzechy/jquery-fileupload/
 * forms (missing)

Thank you :)

**Comment by f3l1x** [comment]
@JZechy Done. Will be in next cache warmup. :-)
