### ISSUE TITLE
Other projects menu does not fit screen on tablet

### ISSUE THREAD

**Issue by patrickkusebauch** [componette/componette.com#24]
On tablet iPad2 in widescreen mode the mane with links to other projects does not fit to one line even though it clearly could. Instead part of it is display over the current page. The screenshot provides details. 

![image](https://cloud.githubusercontent.com/assets/1620948/12307243/5cf30af2-ba3e-11e5-98ff-aa008e6001b3.png)

**Comment by f3l1x** [comment]
@patrickkusebauch Hope its better. Thanks for report.

**Comment by patrickkusebauch** [comment]
Yes, now it looks like this: 
![image](https://cloud.githubusercontent.com/assets/1620948/12307835/20c0f9c8-ba42-11e5-8c71-5ce0cd9d1364.png)
