### ISSUE TITLE
Addon requirements: text wrapping

### ISSUE THREAD

**Issue by wodCZ** [componette/componette.com#28]
Longer requirement should wrap to new line instead of flowing outside.

![](http://i.imgur.com/NSHgzV2.png)

**Comment by f3l1x** [comment]
I'm not sure. I think it's better no wrap.

![](http://i.imgur.com/73HyDs6.png)

**Comment by wodCZ** [comment]
I'm not sure too, but current behavior seemed enough buggy to go and report it here :)

**Comment by f3l1x** [comment]
@wodCZ I dont know better solution now.

**Comment by milo** [comment]
Add title?

**Comment by f3l1x** [comment]
@milo Maybe :)

**Comment by f3l1x** [comment]
@wodCZ It's better now?

**Comment by wodCZ** [comment]
:+1:
