### ISSUE TITLE
Idea: quick composer require input

### ISSUE THREAD

**Issue by wodCZ** [componette/componette.com#29]
While most extensions provide install command, they often include `$` console char on beginning, which complicates copying. Something like npmjs has would be great:

![](http://i.imgur.com/E5Kjd8V.png)

or Github:

![](http://i.imgur.com/QqKEStl.png)

**Comment by f3l1x** [comment]
![untitled_clipping_011916_051253_pm](https://cloud.githubusercontent.com/assets/538058/12424346/0425cdd8-bed0-11e5-9629-d035aacf84f7.jpg)

:hammer: done.
