### ISSUE TITLE
Gulp does not process less

### ISSUE THREAD

**Issue by milo** [componette/componette.com#31]
The Gult task [builds CSS](https://github.com/componette/componette.com/blob/f0e579e56e797d7fe2eea90cb732c6c514bd957f/gulpfile.js#L9) but it is not created from [theme.less](https://github.com/componette/componette.com/blob/f0e579e56e797d7fe2eea90cb732c6c514bd957f/www/assets/css/theme.less).

**Comment by f3l1x** [comment]
Thanks for report. I have had a file watcher at PhpStorm.
