### ISSUE TITLE
Loading resources over insecure protocol

### ISSUE THREAD

**Issue by Majkl578** [componette/componette.com#32]
Take this addon for example (applies to any addon): https://componette.com/uestla/twigrid/

You are loading external images over insecure HTTP protocol.
```
Načítání smíšeného (nezabezpečeného) zobrazovaného obsahu na zabezpečené stránce "http://isitmaintained.com/badge/resolution/uestla/twigrid.svg"[Zjistit více] twigrid
Načítání smíšeného (nezabezpečeného) zobrazovaného obsahu na zabezpečené stránce "http://isitmaintained.com/badge/open/uestla/twigrid.svg"[Zjistit více] twigrid
Načítání smíšeného (nezabezpečeného) zobrazovaného obsahu na zabezpečené stránce "http://i.imgur.com/RHzFX1V.png"[Zjistit více] twigrid
```

**Comment by chemix** [comment]
Nette Forum this issue resolves with cache for all images on own domain. 

solution

parse texy/markdown description, find all images, download all images to local storage, update paths in texty, convert to html and cache it. 

if file is not exists, replace path to default image (something like small [wrong image])

when downloading images to local path check if is sure only images

all these:  *.jpg, *.png, *.jpeg, *.gif, *.svg

**Comment by f3l1x** [comment]
1) I change isitmaintained badges to HTTPS

2) I dont think we need it right now. I could put it to roadmap, but at this time. I plan other things.

**Comment by chemix** [comment]
:+1:

**Comment by chemix** [comment]
PR is welcome @Majkl578 ;-)

**Comment by f3l1x** [comment]
Content fixed via loading readme in HTML format from Github.
