### ISSUE TITLE
ALPN broken?

### ISSUE THREAD

**Issue by Majkl578** [componette/componette.com#34]
It looks like ALPN negotiation to use HTTP/2 fails for some reason on componette.com.
Recent version of Firefox for example seems to work fine over HTTP/2, but e.g. cURL fails to negotiate HTTP/2 via ALPN.

```
$ curl -v --http2 https://componette.com/ > /dev/null 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 81.2.241.154...
* Connected to componette.com (81.2.241.154) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 700 certificates in /etc/ssl/certs
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: componette.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=componette.com
* 	 start date: Fri, 08 Jan 2016 14:18:00 GMT
* 	 expire date: Thu, 07 Apr 2016 14:18:00 GMT
* 	 issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X1
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET / HTTP/1.1
> Host: componette.com
> User-Agent: curl/7.46.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Wed, 27 Jan 2016 17:49:04 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Frame-Options: SAMEORIGIN
< X-Powered-By: componette
< X-XSS-Protection: 1; mode=block
< Vary: X-Requested-With
< Content-Security-Policy: upgrade-insecure-requests
```

If you check SSLLabs, it reports ALPN as disabled: https://www.ssllabs.com/ssltest/analyze.html?d=componette.com
You are using NPN though, which is deprecated.

**Comment by f3l1x** [comment]
Do you know how to fix it?

**Comment by Majkl578** [comment]
Not sure, I'd need to know more about your environment & nginx configuration. Assuming you are using experimental nginx h2 support, it requires OpenSSL 1.0.2+ in order to support ALPN, which is not part of stable Debian tree for example.
Ping me on Gitter if you need.

**Comment by f3l1x** [comment]
I've decided for a keeping older openssl. I will wait for debian official dist package. I hope you don't mind. Thanks for help. Felix.

**Comment by Majkl578** [comment]
Ok, see you in 2 years. ;)

**Comment by Majkl578** [comment]
By the way, Chrome is dropping NPN support on May 15th, so no HTTP/2 for Chrome users after that date. (They already did it last year on november, but decided to extend the support for another half a year.)

**Comment by f3l1x** [comment]
Oh, I didn't know it. I will fix it around 15th of May.

**Comment by Majkl578** [comment]
The day has already came so now componette.com over HTTP/2 is no longer working in Chrome, since version 51.

**Comment by f3l1x** [comment]
Is it better now @Majkl578?

**Comment by f3l1x** [comment]
I think that nginx from 1.9.x does not more support SPDY.

> HTTP/2 support: The SPDY module was replaced by the HTTP/2 module. HTTP/2 support was recently updated to support unbuffered reads for requests.

- https://www.nginx.com/blog/nginx-1-10-1-11-released/
- http://nginx.org/en/docs/http/ngx_http_spdy_module.html

-----

It's ok by me. Is it by you too?

**Comment by milo** [comment]
@f3l1x The problem is not SPDY vs. HTTP/2 protocol, but in SSL version. Chrome now uses ALPN type of TLS negotiation only. It is supported since OpenSSL 1.0.2. And Nginx has to be compiled with it, not only running with it.

Maybe there is already prepared Debian Nginx package, but I don't know about it. There is not even official backported OpenSSL version from Stretch to Jessie, but you can [install it](https://packages.debian.org/stretch/openssl) in parallel. And IMHO the most convenient way is to download official Nginx's [source package](http://nginx.org/en/linux_packages.html#stable) and recompile it with path to newest OpenSSL lib, maybe statically.

Personaly, I would wait few months. But for now, even Dotdeb don't want to [solve it](https://www.dotdeb.org/2016/06/02/nginx-1-10-1-for-jessie-and-wheezy/) :)

**Comment by JanTvrdik** [comment]
> Personaly, I would wait few months.

:+1:

**Comment by Majkl578** [comment]
My suggestion is use packages either directly from nginx.com or from dotdeb.org. You can also use nginx from stretch (testing). SInce you run everything in docker containers, there should be low risk of anything related to version of OpenSSL.

**Comment by JanTvrdik** [comment]
@Majkl578 Do you think you can send PR to https://github.com/componette/dockerfiles?

**Comment by milo** [comment]
@Majkl578 Binary packages from nginx.com are build against matching OpenSSL versions from Wheeze & Jessie. So it does not help.

> That means wait for next Debian release, which should come no sooner than spring 2017.

Not necessarily. Someone can create an backports or publish own builds.

**Comment by f3l1x** [comment]
Thank you guys for you responses. :+1: 

-----

There is debian sid based containers in nginx/proxy.

```
nginx version: nginx/1.11.1
built by gcc 4.9.2 (Debian 4.9.2-10) 
built with OpenSSL 1.0.1k 8 Jan 2015 (running with OpenSSL 1.0.2d 9 Jul 2015)
```

You were right, nginx has to be build with openssl.

Official nginx docker image is also build on top of debian jessie. (https://github.com/nginxinc/docker-nginx/blob/11fc019b2be3ad51ba5d097b1857a099c4056213/mainline/jessie/Dockerfile)

I'm not quite good in compiling of nginx. So, if you don't mind I would wait for others. Or if you have skill to do it, I cannot be more happy and grateful.
