### ISSUE TITLE
[graphic] RFC for new logo

### ISSUE THREAD

**Issue by f3l1x** [componette/componette.com#38]
Suggestions: 

![cy9y0mfwcaaddfw](https://cloud.githubusercontent.com/assets/538058/12639372/4fd7b91e-c5a4-11e5-8892-fc272e6fc362.png)

@chemix

**Comment by chemix** [comment]
give me little time :)

**Comment by milo** [comment]
One :+1: from desing analphabet

**Comment by f3l1x** [comment]
ping @chemix

**Comment by chemix** [comment]
it's better than actual, but it's not final for me :-) but I don't know how to redraw it, yet

**Comment by f3l1x** [comment]
@chemix ping :-)

**Comment by chemix** [comment]
I will ask my designers from atelier ;-) (on friday)

**Comment by f3l1x** [comment]
![selection_013](https://cloud.githubusercontent.com/assets/538058/16384691/36f0f2aa-3c8a-11e6-85ad-87b2cc3f6601.png)

What about something like that? Different colors, hm, hm? 

@chemix @milo

**Comment by chemix** [comment]
looks like frogs in the lake :) but the idea behind it is great. Components together make application, and some components wokrs together too.

**Comment by f3l1x** [comment]
We really need a great graphic designer. :pray:

**Comment by f3l1x** [comment]
@chemix Bump. :-)

**Comment by chemix** [comment]
I'm wokring on elephpant for pehapkari now... 

but idea is something like this ![patternl](http://unmatchedstyle.com/wp-content/uploads/2014/03/patternlab.jpg)

**Comment by f3l1x** [comment]
What do you think about this logo? Thank you guys for you time.

@milo @dg @JanTvrdik @matej21 @chemix @fprochazka @TomasVotruba 

-----

![](https://cloud.githubusercontent.com/assets/538058/12639372/4fd7b91e-c5a4-11e5-8892-fc272e6fc362.png)

**Comment by TomasVotruba** [comment]
Like it. Especially the shade on right side!

How does look in the whole page design?

**Comment by milo** [comment]
Looks great!

**Comment by f3l1x** [comment]
Picked. Deployed. 

Thanks to everyone.

**Comment by TomasVotruba** [comment]
:+1:
