### ISSUE TITLE
Incorrect package name separator

### ISSUE THREAD

**Issue by Majkl578** [componette/componette.com#41]
I noticed use of `\` as a vendor & name separator on some places, which is incorrect, correct one is `/`.
Some places where this is incorrect:
- package detail - page title;
- most popular in the footer;
- newest in the footer.

**Comment by f3l1x** [comment]
Already fixed - https://github.com/componette/componette.com/commit/d92bf4301a036df8d24f8c97ba13e52716eacf30

:-)
