### ISSUE TITLE
Some of the listed tags have no related packages

### ISSUE THREAD

**Issue by Majkl578** [componette/componette.com#43]
For example `#menu` tag is listed, but when clicked it just shows "No package found." (https://componette.com/search/menu).

**Comment by f3l1x** [comment]
It's under construction. We have to tagged all packages.

**Comment by f3l1x** [comment]
Fixed via https://github.com/componette/componette.com/commit/c3fb13a41002da74d4959b62482f67ad98e0a57b & https://github.com/componette/componette.com/commit/1c15a2f25298da571375d4b64f6f79581a58d91f
