### ISSUE TITLE
Symfony tag

### ISSUE THREAD

**Issue by enumag** [componette/componette.com#46]
I've added my integration of symfony/forms to componette. However there is a ton of nette-forms related packages already so I don't think anyone will notice it there. I think there should be a new tag #symfony for integrations of symfony components (Kdyby/Validator, Kdyby/Console, Kdyby/Translation, Symnedi/EventDispatcher, Symnedi/Security and Arachne/Forms, some others - search for symfony on componette.com).

**Comment by hrach** [comment]
**Add Nextras Tag**: I have added integration of nextras orm for Nette. However, there is a ton of orm related packages, so I don't think anyone will notice.

So, :-1: since it's a different point of view for tagging. The current tags are more function-oriented and are more like categories.

**Comment by enumag** [comment]
I suggested this because there is a Doctrine tag.

**Comment by hrach** [comment]
Hm, well, I would remove it too :)

**Comment by enumag** [comment]
Also please don't take my own package as an argument. It was just what triggered me to suggest this. The reason is that Symfony components are good and when Nette doesn't have a feature many people try to use a related Symfony component. You can't really compare Nextras with Symfony in this regard either.

**Comment by hrach** [comment]
Of course, Nextras Orm is much better.

**Comment by enumag** [comment]
Obviously. :-)

**Comment by f3l1x** [comment]
Well, I would like to keep it simple. First of it, I didn't like to add a symfony tag. Because as @hrach said, it's more function-oriented. But after little thinking, I would like to add it. Symfony and Nette community is connected more then others communities. It could help to stay people at Nette Framework but also use cool packages / addons from / to Symfony and their backports / bridges for Nette.

Do you agree with me? @enumag @hrach

// cc @chemix

**Comment by chemix** [comment]
I think the right tag name is SymfonyComponent https://symfony.com/components. And why we don't need NextrasComponent? In this time, we have Nextras author. So maybe when more authors create some addons for Nextras, we add this tag name....  It's just an another way how find the right component on the platform. If this new tag name help me, thats perfect. But when it's only information noise... hide it.

**Comment by enumag** [comment]
@f3l1x Yeah, this is why I suggested it.

@chemix SymfonyComponent does make sense but is a bit too long imho.

**Comment by f3l1x** [comment]
@enumag Agree. It's too long name.

**Comment by chemix** [comment]
and what? :) nobody will write it. Just click on it and filter similar Symfony componets usable in nette application?

**Comment by hrach** [comment]
Glad I can introduce you the first Nextras extension: https://componette.com/mikulas/nextras-ormext/

**Comment by enumag** [comment]
@hrach This is about symfony tag. Please open a new issue if you believe nextras tag should be added as well. Thanks.

**Comment by f3l1x** [comment]
I think Symfony tag is oukey, same as Doctrine tag. 

I like Nextras, you known I do. Just wait a while it could be there sometime.

**Comment by f3l1x** [comment]
Added tag **symfon** and connect to addons. Thank you.

**Comment by enumag** [comment]
@f3l1x Most of my packages mysteriously lost the symfony tag (I'm sure they had it before). Can you re-add it?

- https://componette.com/arachne/csrf/
- https://componette.com/arachne/propertyaccess/
- https://componette.com/arachne/eventdispatcher/
- https://componette.com/arachne/doctrine/
- https://componette.com/arachne/upload/
- https://componette.com/arachne/expressionlanguage/

Also it seams that my packages never appear in the last activity list even when I make some changes. For example https://github.com/Arachne/EntityLoader is pretty active but on Componette it has last activity 104 days ago. Same problem applies to most of my other packages.

**Comment by enumag** [comment]
@f3l1x Also you can remove https://componette.com/arachne/di-helpers/ - it's deprecated and the repository has been moved to https://github.com/ArachneLegacy/DI-Helpers.

**Comment by f3l1x** [comment]
@enumag Problem with activity solved. There was a problem with a duplicity in cron.

**Comment by f3l1x** [comment]
@enumag I've just add the symfony to your addons.

**Comment by enumag** [comment]
Thank you! https://componette.com/arachne/doctrine/ should have the tag to imho. It relies heavily on symfony/doctrine-bridge.
