### ISSUE TITLE
[Proposal] Package licenses: make it mandatory & disallow open-source-unfriendly licenses?

### ISSUE THREAD

**Issue by Majkl578** [componette/componette.com#50]
This is just an idea, but it may be a good thing to check whether package has a valid license.
Additionally we may also disallow some restrictive licences that don't really fit well in open-source, especially those that require disclosing source AGPL and GPL, maybe also LGPL. Alternatively (at least) show a banner/badge indicating that the package is using such bad license.

**Comment by f3l1x** [comment]
Thanks for an idea. I think we don't need this. Licence badge is in the sidebar and it's up to you if you use it or don't use it or browse a code or whatever.

Is there any other reason then information for you?

**Comment by Majkl578** [comment]
Yes, using unlicenced code or code with bad license could be (is) a legal issue.

**Comment by f3l1x** [comment]
It could be but it's not a problem of componette. Or is it?
