### ISSUE TITLE
Composer copy to clipboard functionality feedback to user

### ISSUE THREAD

**Issue by LeonardoCA** [componette/componette.com#53]
Let the user know the click "worked" same as on github - just change the text of tool tip to "copied' instantly after link is successfully copied to clipboard and reset back to "Click & copy" on mouse out event.

**Comment by f3l1x** [comment]
Great idea. Could you prepare PR?

**Comment by LeonardoCA** [comment]
PR https://github.com/componette/componette.com/pull/54

**Comment by f3l1x** [comment]
Closed via merge: https://github.com/componette/componette.com/pull/54

**Comment by f3l1x** [comment]
Thank you. :+1:

**Comment by f3l1x** [comment]
@LeonardoCA: Deployed.
