### ISSUE TITLE
no link to github

### ISSUE THREAD

**Issue by chemix** [componette/componette.com#55]
https://componette.com/juzna/intellij-neon/

**Comment by f3l1x** [comment]
![screenshot_031416_084211_pm](https://cloud.githubusercontent.com/assets/538058/13757511/24aa3848-ea25-11e5-939b-f9cae1db3db7.jpg)

**Comment by chemix** [comment]
tak to jsem bral ze je odkaz v ramci platformy planette

**Comment by f3l1x** [comment]
@chemix muzu tam pridat treba octocat ikonku

**Comment by hrach** [comment]
stejny problem jsem dnes resit taky!!! .)

**Comment by hrach** [comment]
I would put an icon to the right sidebar, it's a standard in package systems. The link on the top should leand to the current package/vendor list on componette.

**Comment by chemix** [comment]
Inspiration from https://ghbtns.com/

**Comment by f3l1x** [comment]
Closed via: https://github.com/componette/componette.com/commit/6de9f3221e7551649887fd37624a97a8bc0263ac

**Comment by f3l1x** [comment]
![screenshot_031616_025612_pm](https://cloud.githubusercontent.com/assets/538058/13814607/39edbf50-eb87-11e5-9ce8-3809f6ad2d93.jpg)
![screenshot_031616_025628_pm](https://cloud.githubusercontent.com/assets/538058/13814616/438ea114-eb87-11e5-8042-25f857e5c267.jpg)

**Comment by hrach** [comment]
:heart:

**Comment by chemix** [comment]
:+1:
