### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by landsman** [componette/componette.com#67]
Hi,

if i try search "nette ajax" => 0 results. I don´t know that real name is "nette.ajax".

**Comment by f3l1x** [comment]
Thanks for reporting. At this time I don't know how to solve it. Maybe later we can use ElasticSearch. Do you have better idea?

**Comment by artemevsin** [comment]
what about explode search string by words and add each word as `OR LIKE '%word%'` . I'm not sure about performance, but it can helps. 
Prestashop does it in similar way (but use pregenerated indexes) https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Search.php#L194-L219

**Comment by f3l1x** [comment]
@artemevsin Great idea. Could you please test this solution? Especially for `nette.ajax` for string `nette ajax`.

**Comment by artemevsin** [comment]
Fixed in https://github.com/componette/componette.com/pull/81

**Comment by f3l1x** [comment]
Thank you very much :+1:. I test it and probably merge it in few days. :-)

**Comment by f3l1x** [comment]
Closed via #81
