### ISSUE TITLE
Packages in queue

### ISSUE THREAD

**Issue by besir** [componette/componette.com#69]
Pridal jsem novy balicek a dole na webu se nezobrazuje ze je neco ve fronte

**Comment by f3l1x** [comment]
Sablony jsou cachovane, myslim ze footer na 1h nebo tak. :-)

**Comment by f3l1x** [comment]
Melo by to byt opravene a nasazene. https://github.com/componette/componette.com/commit/f03cbb0496e1f76fa4de1cac8dd23b289794c0ee

**Comment by f3l1x** [comment]
Zaviram. Diky za report.

@besir :+1:

**Comment by besir** [comment]
(y)
