### ISSUE TITLE
Flash message after adding new package

### ISSUE THREAD

**Issue by enumag** [componette/componette.com#70]
Yesterday I've added some packages but they are still not visible and the queue count in footer is 0 too (for way longer than 1 hour as mentioned in #69).

I've looked in the code and found out that the package addition might be broken. The thing is I never got any flash message (no success nor error) so either the flash messages are broken or some unexpected exception was thrown - only UniqueConstraintViolationException and PDOException are cought (https://github.com/componette/componette.com/blob/34ad73d01e6841ef8aa3e20194142a658e171af9/app/modules/Front.Portal/controls/AddonModal/AddonModal.php#L79-L86). Can you investigate?

**Comment by f3l1x** [comment]
@enumag You are right. Should be fixed now.

**Comment by enumag** [comment]
@f3l1x Was it just flash message or was it broken completely? Do I need to add my packages again?

**Comment by f3l1x** [comment]
You have to add your packages again. It was an issue in Nette 2.4-dev (no `do` parameter in form). Sorry. :(

**Comment by enumag** [comment]
Understood. Thank you!
