### ISSUE TITLE
Strange redirect after adding addon

### ISSUE THREAD

**Issue by enumag** [componette/componette.com#73]
When I add a new addon I get redirected to https://componette.com/repli2dev/tracy-gitversion-panel.

**Comment by f3l1x** [comment]
Thanks for report. It's already fixed in master. It will be in next release.

**Comment by enumag** [comment]
Ah. Ok. :-)

**Comment by f3l1x** [comment]
I thank you. :+1:

**Comment by JanTvrdik** [comment]
@f3l1x You should set up continuous deployment process.

**Comment by f3l1x** [comment]
It's already in my plan. @JanTvrdik :rocket:
