### ISSUE TITLE
Addon disqus

### ISSUE THREAD

**Issue by f3l1x** [componette/componette.com#75]
Add simple widget from https://disqus.com/ to chance write a short feedback.

**Comment by JanTvrdik** [comment]
Not sure it is worth it, it creates another channel which the addon author should read.

**Comment by f3l1x** [comment]
Do you see any other possible channel/way how to thanks for an addon in public? Or write a short feedback? I would like to give a place for it.

**Comment by chemix** [comment]
like on github :) and teach users to use github for issues

**Comment by f3l1x** [comment]
@chemix Thanks for feedback. I am not really sure that creating issues is the best way to say thank you. :smiley: Or maybe it is.

**Comment by chemix** [comment]
nooo  :)   teach them to use likes (hearts) on github for feedback, not for "bookmarks", and teach them use github issues for questions and issues...   ;-)

**Comment by f3l1x** [comment]
@chemix @JanTvrdik Ok, you lawyered me.

![image](https://cloud.githubusercontent.com/assets/538058/19191594/76d24cf2-8ca3-11e6-9279-a71a5b33f6b3.png)
