### ISSUE TITLE
Report (delete) - mrtnzlml packages, update Adeira

### ISSUE THREAD

**Issue by mrtnzlml** [componette/componette.com#76]
Those addons are deprecated, you can delete them.

- [ ] `mrtnzlml/monolog` (replaced by `adeira/monolog`)
- [ ] `mrtnzlml/compiler-extension` (replaced by `adeira/compiler-extension`)
- [ ] `mrtnzlml/csp` (replaced by `adeira/csp`)

Also there is wrong (old) organization profile image: https://componette.com/adeira/ (see: https://github.com/adeira)

Thank you.

**Comment by f3l1x** [comment]
- [x] delete old addons
- [x] update avatar cache

![selection_001](https://cloud.githubusercontent.com/assets/538058/19486621/68ddd8ae-955f-11e6-9489-3e34609aac21.png)

**Comment by f3l1x** [comment]
Thank for reporting. :+1:

**Comment by mrtnzlml** [comment]
Gracias @f3l1x... :slightly_smiling_face:
