### ISSUE TITLE
Package requirements - drop nowrap

### ISSUE THREAD

**Issue by enumag** [componette/componette.com#77]
On the package detail page the requiremens have `white-space: nowrap;` applied making some of the required versions invisible.

It might be a good idea to drop the list-type and padding-left as well to get more space.

**Comment by enumag** [comment]
Also how about a new release? It has been several months. ;-)

**Comment by f3l1x** [comment]
Shame on me about new releases, I know that. :( Unfortunately I don't have much time until now.
