### ISSUE TITLE
Can you elaborate how to run in readme?

### ISSUE THREAD

**Issue by enumag** [componette/componette.com#78]
I'd like to run this locally and maybe send a PR occasionly. So far I'm discouraged from doing so by a small negligence in readme:

- Create database and setup tables (and fixtures)

Could you elaborate how to do that? I've zero experience with nextras/migrations.

**Comment by JanTvrdik** [comment]
For same reason @f3l1x does not use the Symfony commands (which is usually how to execute nextras migrations) but uses the HTTP interface, so just open in browser `https://localhost/componette.com/migrations/run.php`

**Comment by f3l1x** [comment]
I'll try to rewritte better readme.

@JanTvrdik https://github.com/componette/componette.com/issues/71 - I would like to use it. :+1:
